version: '3.7'

services:

  mysql:
    container_name: rumox-test-mysql
    volumes:
      - rumox-test-mysql-vol:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test

  mongo:
    container_name: rumox-test-mongo
    volumes:
      - rumox-test-mongo-vol:/data/db
    ports:
      - 27017:27017

  redis:
    ports:
      - 6379:6379
      
volumes:
  rumox-test-mysql-vol:
  rumox-test-mongo-vol: