version: '3.7'

services:

  mysql:
    build:
      context: ./sql/catalogo
      dockerfile: MySQL.dockerfile
    container_name: rumox-mysql
    volumes:
      - rumox-mysql-vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rumoxdb
    networks:
      - rumox-net
    command: --sql_mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

networks:
  rumox-net:

volumes:
  rumox-mysql-vol:
