

metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "image", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

- module: elasticsearch
  metricsets: ["node", "node_stats", "cluster_stats", "index"]
  period: 10s
  hosts: ["elasticsearch:9200"]  

- module: rabbitmq
  metricsets: ["exchange", "connection", "node", "queue"]
  period: 10s
  hosts: ["rabbitmq:15672"]
  username: logUser
  password: logPwd


output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#  username: "elastic"
#  password: "elastic"
setup.kibana:
  host: "kibana:5601"  
#  username: "elastic" 
#  password: "elastic"  


setup.dashboards.enabled: true
